"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, ChevronRight, FileUp, Link2, RefreshCw, Save, Search, X } from "lucide-react";
import { getActiveAcademicContextAction, listCurriculumIntelligenceAction, adoptCurriculumItemsAction } from "../mata-pelajaran/curriculum-actions";

type Source={id:string;institution:string;name:string;official_url:string;status:string};
type Version={id:string;source_id:string;curriculum_name:string;regulation_number:string|null;regulation_year:number|null;regulation_title:string|null;effective_status:string;document_url:string|null;verification_status:string};
type Item={id:string;curriculum_version_id:string;subject_name:string;class_level:string;allocation_unit:string|null;official_allocation:number|null;weekly_target:number|null;derivation_status:string;extraction_status:string};
type Context={id:string;tahun_pelajaran:string;semester:string;is_active:boolean};
type Kelas={id:string;tingkat:string;nama_rombel:string;tahun_ajaran:string;semester:string};
type Candidate=Item&{target:number|null};
type Filter="all"|"new"|"changed"|"review";

export default function GenerateKurikulumV4(){
 const [sources,setSources]=useState<Source[]>([]),[versions,setVersions]=useState<Version[]>([]),[items,setItems]=useState<Item[]>([]),[contexts,setContexts]=useState<Context[]>([]),[classes,setClasses]=useState<Kelas[]>([]);
 const [versionId,setVersionId]=useState(""),[level,setLevel]=useState(""),[classIds,setClassIds]=useState<string[]>([]),[candidate,setCandidate]=useState<Candidate[]>([]),[baseline,setBaseline]=useState<Record<string,number|null>>({});
 const [query,setQuery]=useState(""),[filter,setFilter]=useState<Filter>("all"),[selected,setSelected]=useState<string[]>([]),[contextOpen,setContextOpen]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[updateOpen,setUpdateOpen]=useState(false),[compareOpen,setCompareOpen]=useState(false),[success,setSuccess]=useState(false);
 const [updateMode,setUpdateMode]=useState<"previous"|"new">("previous"),[sourceUrl,setSourceUrl]=useState(""),[fileName,setFileName]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(true),[progress,setProgress]=useState(0),[committing,setCommitting]=useState(false);
 const activeContext=contexts.find(c=>c.is_active)??null;
 const verified=useMemo(()=>versions.filter(v=>v.verification_status==="verified"),[versions]);
 const activeVersion=versions.find(v=>v.id===versionId)??null;
 const activeSource=sources.find(s=>s.id===activeVersion?.source_id)??null;
 const levels=useMemo(()=>Array.from(new Set(items.filter(i=>i.curriculum_version_id===versionId).map(i=>i.class_level))),[items,versionId]);
 const eligibleClasses=classes.filter(c=>(!level||c.tingkat===level)&&(!activeContext||c.tahun_ajaran===activeContext.tahun_pelajaran)&&(!activeContext||c.semester===activeContext.semester));
 const validItems=items.filter(i=>i.curriculum_version_id===versionId&&(!level||i.class_level===level)&&i.extraction_status==="verified"&&i.derivation_status!=="blocked");
 const changed=candidate.filter(x=>x.target!==baseline[x.id]);
 const fresh=candidate.filter(x=>baseline[x.id]===undefined);
 const review=candidate.filter(x=>x.target===null||!Number.isInteger(x.target)||x.target<0);
 const total=candidate.reduce((s,x)=>s+(x.target??0),0),official=candidate.reduce((s,x)=>s+(x.official_allocation??0),0);
 const visible=candidate.filter(x=>x.subject_name.toLowerCase().includes(query.toLowerCase())).filter(x=>filter==="all"||(filter==="changed"&&changed.some(y=>y.id===x.id))||(filter==="new"&&fresh.some(y=>y.id===x.id))||(filter==="review"&&review.some(y=>y.id===x.id)));
 const ready=!!activeContext&&!!activeVersion&&activeVersion.verification_status==="verified"&&classIds.length>0;

 useEffect(()=>{let live=true;(async()=>{const [ci,ctx]=await Promise.all([listCurriculumIntelligenceAction("all"),getActiveAcademicContextAction()]);if(!live)return;if(ci.ok){setSources(ci.data.sources as Source[]);setVersions(ci.data.versions as Version[]);setItems(ci.data.items as Item[]);const v=(ci.data.versions as Version[]).filter(x=>x.verification_status==="verified");if(v.length===1)setVersionId(v[0].id);}else setMessage(ci.error);if(ctx.ok){setContexts(ctx.data.contexts as Context[]);setClasses(ctx.data.classes as Kelas[]);}else setMessage(ctx.error);setBusy(false)})();return()=>{live=false}},[]);
 useEffect(()=>{if(!activeContext||!classes.length)return;const ids=classes.filter(c=>c.tahun_ajaran===activeContext.tahun_pelajaran&&c.semester===activeContext.semester).map(c=>c.id);setClassIds(ids)},[activeContext,classes]);
 useEffect(()=>{if(activeVersion&&levels.length===1)setLevel(levels[0])},[activeVersion,levels]);

 function chooseVersion(id:string){setVersionId(id);setLevel("");setCandidate([]);setBaseline([] as never);setSelected([]);setProgress(0);setSuccess(false)}
 function generate(){if(!ready)return;setSuccess(false);setProgress(1);let n=1;const timer=setInterval(()=>{n++;setProgress(n);if(n>=5){clearInterval(timer);const next=validItems.map(i=>({...i,target:i.weekly_target}));setCandidate(next);setBaseline(Object.fromEntries(next.map(i=>[i.id,i.weekly_target])));setMessage(next.length?"Kurikulum siap ditinjau ✓":"Tidak ada data valid untuk digenerate.");}},180)}
 function edit(id:string,value:string){setCandidate(c=>c.map(x=>x.id===id?{...x,target:value===""?null:Number(value)}:x))}
 function restore(id:string){setCandidate(c=>c.map(x=>x.id===id?{...x,target:baseline[id]??x.weekly_target}:x))}
 function bulk(){const raw=window.prompt("Target JP baru");if(raw===null)return;const n=Number(raw);if(!Number.isInteger(n)||n<0)return;setCandidate(c=>c.map(x=>selected.includes(x.id)?{...x,target:n}:x));setSelected([])}
 async function sync(){if(!activeContext||!candidate.length||review.length)return;setCompareOpen(false);setCommitting(true);const r=await adoptCurriculumItemsAction({academicContextId:activeContext.id,classIds,items:candidate.map(x=>({id:x.id,weeklyTarget:x.target}))});setCommitting(false);if(r.ok){setSuccess(true);setMessage(`Kurikulum tersimpan · ${r.data.adopted} kombinasi`)}else setMessage(r.error)}

 const contextText=activeContext?`${activeContext.tahun_pelajaran} · ${activeContext.semester==="ganjil"?"Ganjil":"Genap"}`:"Konteks akademik belum siap";
 return <div className="mx-auto max-w-6xl space-y-5 pb-28">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/akademik/mata-pelajaran" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><ArrowLeft className="h-4 w-4"/>Kembali</Link><h1 className="mt-3 text-3xl font-bold tracking-tight text-ink-900">Generate Kurikulum</h1><p className="mt-1 max-w-2xl text-sm text-ink-600">SAKALA membaca konteks → menyiapkan sumber → generate → operator meninjau → sinkronisasi aman.</p></div><button onClick={()=>setUpdateOpen(true)} className="inline-flex items-center gap-2 rounded-xl border border-brand-300 px-5 py-3 text-sm font-bold text-brand-700"><RefreshCw className="h-4 w-4"/>Update</button></header>
  <section className="relative rounded-2xl border border-brand-200 bg-brand-50 p-4"><button onClick={()=>setContextOpen(v=>!v)} className="flex w-full items-center justify-between text-left"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-brand-700">Konteks Aktif</p><p className="mt-1 font-bold text-brand-950">{activeContext?`SMP/MTs · Kemenag · ${contextText}`:contextText}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${activeContext?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{activeContext?"✓ Konteks siap":"⚠ Konteks belum lengkap"}</span></button>{contextOpen&&<div className="absolute left-4 right-4 top-full z-40 mt-2 rounded-xl border bg-surface p-4 shadow-lg"><p className="font-bold">Konteks Akademik</p><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><span>Jenjang — SMP/MTs</span><span>Kementerian — Kemenag</span><span>Tahun — {activeContext?.tahun_pelajaran??"—"}</span><span>Semester — {activeContext?contextText.split(" · ")[1]:"—"}</span></div><Link href="/pengaturan/konteks-akademik" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-brand-700">Buka Konteks Akademik<ChevronRight className="h-4 w-4"/></Link></div>}</section>
  {!candidate.length?<>
   <section className="rounded-2xl border bg-surface p-5 shadow-soft"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Kurikulum</p><h2 className="mt-1 text-xl font-bold">{activeVersion?.curriculum_name??"Belum dipilih"} {activeVersion&&<span className="text-emerald-600">✓</span>}</h2><p className="text-sm text-ink-600">{activeVersion?`Kemenag · ${activeVersion.regulation_year??"tahun tidak dicantumkan"}`:"Pilih otomatis bila hanya satu versi verified."}</p></div><button onClick={()=>setUpdateOpen(true)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Update</button></div>{verified.length>1&&<select value={versionId} onChange={e=>chooseVersion(e.target.value)} className="mt-4 w-full rounded-xl border p-3"><option value="">Pilih kurikulum</option>{verified.map(v=><option key={v.id} value={v.id}>{v.curriculum_name} · {v.regulation_year??"—"}</option>)}</select>}</section>
   <section className="rounded-2xl border bg-surface p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Sumber & Referensi</p><p className="mt-1 font-semibold">{activeSource?.name??"Belum tersedia"}</p><p className="text-sm text-ink-600">{activeSource?.institution??"—"} · {activeVersion?.regulation_year??"—"}</p></div><div className="flex gap-2"><button onClick={()=>setSourceOpen(true)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Lihat detail</button><button onClick={()=>setUpdateOpen(true)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Update Sumber</button></div></div><div className="mt-3 text-sm font-semibold text-emerald-700">{activeSource&&activeVersion?.verification_status==="verified"?"✓ Sumber siap":"⚠ Sumber perlu ditinjau"}</div></section>
   <section className="rounded-2xl border bg-surface p-5"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${activeContext?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{activeContext?"✓ Konteks siap":"⚠ Konteks belum lengkap"}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${activeVersion?.verification_status==="verified"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{activeVersion?.verification_status==="verified"?"✓ Kurikulum siap":"⚠ Kurikulum belum siap"}</span><span className="text-sm text-ink-500">{eligibleClasses.length} kelas sesuai konteks</span></div>{levels.length>1&&<select value={level} onChange={e=>setLevel(e.target.value)} className="mt-4 rounded-xl border p-3"><option value="">Semua jenjang</option>{levels.map(l=><option key={l}>{l}</option>)}</select>}<button disabled={!ready||busy} onClick={generate} className="mt-5 w-full rounded-xl bg-brand-700 px-5 py-4 text-base font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Generate Kurikulum</button><p className="mt-2 text-center text-xs text-ink-500">{ready?"Konteks siap · Kurikulum siap · Sumber siap":"Menunggu prerequisite…"}</p></section>
   {progress>0&&<section className="rounded-2xl border bg-surface p-4 text-sm">Membaca sumber {progress>=1?"✓":"○"} · Menentukan struktur {progress>=2?"✓":"○"} · Menyiapkan mata pelajaran {progress>=3?"✓":"○"} · Membaca JP {progress>=4?"✓":"○"} · Menyiapkan hasil {progress>=5?"✓":"○"}</section>}
  </>:<>
   <section className="rounded-2xl border bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Hasil Generate</p><p className="mt-1 font-bold">{candidate.length} mata pelajaran</p></div><span className="text-sm text-ink-600">{candidate.length-changed.length-fresh.length} tetap · {changed.length} berubah · {fresh.length} baru</span></div><div className="mt-4 flex flex-wrap gap-2">{([['all',candidate.length,'Total'],['changed',changed.length,'Berubah'],['new',fresh.length,'Baru'],['review',review.length,'Perlu ditinjau']] as const).map(([f,n,label])=><button key={f} onClick={()=>setFilter(f)} className={`rounded-full px-3 py-2 text-sm font-semibold ${filter===f?'bg-brand-700 text-white':'bg-surface-muted text-ink-700'}`}>{n} {label}</button>)}</div></section>
   <section className="rounded-2xl border bg-surface p-5"><div className="flex flex-wrap gap-3"><div className="relative flex-1 min-w-[220px]"><Search className="absolute left-3 top-3 h-4 w-4 text-ink-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari mata pelajaran…" className="w-full rounded-xl border py-2.5 pl-9 pr-3"/></div>{selected.length>0&&<><button onClick={bulk} className="rounded-xl border px-3 py-2 text-sm font-semibold">Atur Target JP</button><button onClick={()=>setSelected([])} className="rounded-xl border px-3 py-2 text-sm">Batalkan</button></>}</div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-ink-500"><th className="w-10 py-3"></th><th className="py-3">Mata Pelajaran</th><th className="py-3">JP Resmi</th><th className="py-3">Target JP</th><th className="py-3">Status</th><th></th></tr></thead><tbody>{visible.map(x=>{const isChanged=x.target!==baseline[x.id],isNew=baseline[x.id]===undefined;return <tr key={x.id} className="border-b last:border-0"><td className="py-3"><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>setSelected(s=>s.includes(x.id)?s.filter(id=>id!==x.id):[...s,x.id])}/></td><td className="py-3 font-semibold">{x.subject_name}<div className="text-xs font-normal text-ink-500">{x.class_level}</div></td><td className="py-3">{x.official_allocation??"—"}</td><td className="py-3"><input type="number" min="0" value={x.target??""} onChange={e=>edit(x.id,e.target.value)} className="w-20 rounded-lg border px-2 py-1 font-semibold"/>{isChanged&&<div className="text-[11px] text-brand-700">{baseline[x.id]??"—"} → {x.target??"—"} <button onClick={()=>restore(x.id)} className="ml-1 underline">Kembalikan</button></div>}</td><td className="py-3">{isNew?<span className="text-blue-700">Baru</span>:isChanged?<span className="text-amber-700">Berubah</span>:review.some(y=>y.id===x.id)?<span className="text-amber-700">Perlu ditinjau</span>:<span className="text-emerald-700">Tetap</span>}</td><td className="py-3 text-right"><button onClick={()=>setMessage(`${x.subject_name} · ${x.official_allocation??"—"} JP resmi · target ${x.target??"—"} JP`)} className="text-brand-700 font-semibold">Detail</button></td></tr>})}</tbody></table></div></section>
   <section className="rounded-2xl border bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-ink-500">Total Target JP</p><p className="text-2xl font-bold">{total}</p><p className="text-xs text-ink-500">JP resmi: {official} · Perubahan: {total-official>=0?"+":""}{total-official} JP</p></div><div className="text-sm">{review.length?<span className="text-amber-700">⚠ {review.length} perlu ditinjau</span>:<span className="text-emerald-700">✓ Target diterima</span>}</div></div></section>
   {candidate.some(x=>x.target!==baseline[x.id])&&<div className="fixed inset-x-0 bottom-0 z-30 border-t bg-surface/95 p-3 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><span className="text-sm font-semibold">{changed.length} perubahan belum disimpan</span><button disabled={!!review.length||committing} onClick={()=>setCompareOpen(true)} className="rounded-xl bg-brand-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Simpan & Sinkronkan</button></div></div>}
  </>}
  {message&&<div className="rounded-xl border bg-surface-muted p-3 text-sm">{message}</div>}
  {sourceOpen&&<div className="fixed inset-0 z-50 bg-black/20" onClick={()=>setSourceOpen(false)}><aside onClick={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full max-w-md bg-surface p-6 shadow-2xl"><button onClick={()=>setSourceOpen(false)} className="float-right"><X/></button><p className="text-xs uppercase tracking-wide text-ink-500">Source Preview</p><h2 className="mt-2 text-2xl font-bold">{activeVersion?.curriculum_name??"Kurikulum"}</h2><p className="text-sm text-ink-600">{activeSource?.institution??"—"} · {activeVersion?.regulation_year??"—"}</p><div className="mt-6 space-y-3 text-sm"><p>✓ Siap digunakan</p><p>Regulasi resmi</p><p>Terakhir digunakan — {activeVersion?.regulation_year??"—"}</p></div><div className="mt-6 flex gap-2"><button onClick={()=>setSourceOpen(false)} className="rounded-xl bg-brand-700 px-4 py-3 font-bold text-white">Gunakan sumber</button><button onClick={()=>setSourceOpen(false)} className="rounded-xl border px-4 py-3">Tutup</button></div></aside></div>}
  {updateOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/20 p-4"><div className="w-full max-w-lg rounded-2xl bg-surface p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Perbarui sumber / kurikulum</h2><button onClick={()=>setUpdateOpen(false)}><X/></button></div><p className="mt-2 text-sm text-ink-600">Menggunakan konteks aktif: {contextText}</p><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>setUpdateMode("previous")} className={`rounded-xl border p-3 text-sm font-semibold ${updateMode==="previous"?'border-brand-500 bg-brand-50':''}`}>Sumber tersimpan</button><button onClick={()=>setUpdateMode("new")} className={`rounded-xl border p-3 text-sm font-semibold ${updateMode==="new"?'border-brand-500 bg-brand-50':''}`}>Sumber baru</button></div>{updateMode==="previous"?<div className="mt-4 max-h-56 space-y-2 overflow-auto">{verified.map(v=><button key={v.id} onClick={()=>{setVersionId(v.id);setUpdateOpen(false)}} className="w-full rounded-xl border p-3 text-left"><b>{v.curriculum_name}</b><div className="text-xs text-ink-500">{v.regulation_year??"—"} · verified</div></button>)}</div>:<div className="mt-4 space-y-3"><label className="flex items-center gap-2 rounded-xl border p-3"><Link2 className="h-4 w-4"/><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Link sumber" className="w-full outline-none"/></label><label className="flex items-center gap-2 rounded-xl border p-3"><FileUp className="h-4 w-4"/><input type="file" onChange={e=>setFileName(e.target.files?.[0]?.name??"")} className="w-full text-sm"/></label><p className="text-xs text-ink-500">Sumber baru tidak boleh menimpa data resmi sampai diverifikasi.</p></div>}<button onClick={()=>setUpdateOpen(false)} className="mt-5 w-full rounded-xl bg-brand-700 px-4 py-3 font-bold text-white">Selesai</button></div></div>}
  {compareOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/20 p-4"><div className="w-full max-w-lg rounded-2xl bg-surface p-6 shadow-2xl"><h2 className="text-xl font-bold">Perubahan ditemukan</h2><p className="mt-1 text-sm text-ink-600">{changed.length} perubahan perlu disimpan.</p><div className="mt-4 space-y-2 text-sm">{changed.slice(0,6).map(x=><p key={x.id}>• {x.subject_name}: {baseline[x.id]??"—"} → {x.target??"—"}</p>)}{fresh.length>0&&<p>• {fresh.length} mata pelajaran baru</p>}</div><div className="mt-6 flex flex-wrap justify-end gap-2"><button onClick={()=>setCompareOpen(false)} className="rounded-xl border px-4 py-3">Tinjau perbedaan</button><button onClick={sync} className="rounded-xl bg-brand-700 px-4 py-3 font-bold text-white">Gunakan hasil terbaru</button></div></div></div>}
  {success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 font-bold text-emerald-800"><Check className="h-5 w-5"/>Kurikulum tersimpan</div><p className="mt-2 text-sm text-emerald-800">{candidate.length} mata pelajaran · data committed ke Active Academic Context.</p><div className="mt-4 flex gap-2"><Link href="/akademik/mata-pelajaran" className="rounded-xl bg-brand-700 px-4 py-3 text-sm font-bold text-white">Lihat Mata Pelajaran</Link><Link href="/akademik/target-jp" className="rounded-xl border px-4 py-3 text-sm font-bold">Lihat Target JP</Link></div></div>}
 </div>
}