"use client";

// SAKALA MASTER RULE (Core Consolidation / Zero Duplicate Information):
// Sebelumnya ini halaman terpisah (/akademik/target-jp) -- operator harus
// pindah halaman untuk berpindah antara "lihat detail Target JP" dan
// "import/edit massal Target JP", padahal keduanya bekerja pada data yang
// sama persis (dan sejak PR #90 sudah satu jalur tulis: upsertTargetJp()).
// Sekarang jadi panel yang bisa dibuka/tutup di dalam satu halaman
// TargetJpWorkspace -- logic di bawah ini dipindah verbatim dari halaman
// lama, tidak ditulis ulang, supaya perilaku persis sama (evidence-first,
// tidak menyentuh yang sudah benar tanpa alasan).
import { DragEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

const cols = ["AcademicContext", "Kelas", "KodeMapel", "MataPelajaran", "TargetJP"];
type Row = Record<string, string>;
type Result = { row: number; status: "valid" | "warning" | "error"; message: string; data?: Row };
type Master = { id: string; label: string; code?: string };
type Target = { academic_context_id: string; kelas_id: string; mata_pelajaran_id: string; target_jp: number };
type DetailMode = "all" | "filled" | "empty" | "jp" | null;

export default function TargetJpImportPanel({ onSaved }: { onSaved?: () => void }) {
  const router = useRouter();
  const [rows, setRows] = useState<Row[]>([]); const [results, setResults] = useState<Result[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [dragActive, setDragActive] = useState(false); const [showImport, setShowImport] = useState(false); const [detailMode, setDetailMode] = useState<DetailMode>(null);
  const [contexts, setContexts] = useState<Master[]>([]); const [classes, setClasses] = useState<Master[]>([]); const [subjects, setSubjects] = useState<Master[]>([]); const [targets, setTargets] = useState<Target[]>([]);
  const [manualContext, setManualContext] = useState(""); const [manualClass, setManualClass] = useState(""); const [manualSubject, setManualSubject] = useState(""); const [manualJp, setManualJp] = useState(0);

  async function loadData() { const res = await fetch("/api/target-jp/import?mode=data", { cache: "no-store" }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Gagal memuat data Target JP."); setContexts((json.contexts ?? []).map((c: any) => ({ id: c.id, label: `${c.tahun_pelajaran} · ${c.semester}` }))); setClasses((json.classes ?? []).map((c: any) => ({ id: c.id, label: `${c.tingkat} ${c.nama_rombel}` }))); setSubjects((json.subjects ?? []).map((s: any) => ({ id: s.id, label: s.nama, code: s.kode ?? "" }))); setTargets(json.targets ?? []); if (json.contexts?.[0]) setManualContext(json.contexts[0].id); }
  useEffect(() => { loadData().catch((e) => setMessage(e instanceof Error ? e.message : "Gagal memuat data.")); }, []);
  const targetMap = useMemo(() => new Map(targets.map((t) => [`${t.academic_context_id}:${t.kelas_id}:${t.mata_pelajaran_id}`, t.target_jp])), [targets]);
  const totalTarget = targets.length; const filledTarget = targets.filter(t => t.target_jp > 0).length; const zeroTarget = targets.filter(t => t.target_jp === 0).length; const totalJp = targets.reduce((s, t) => s + Number(t.target_jp || 0), 0); const existingJp = targetMap.get(`${manualContext}:${manualClass}:${manualSubject}`);
  const selectedClass = classes.find(c => c.id === manualClass); const selectedContext = contexts.find(c => c.id === manualContext);
  const detailRows = useMemo(() => { if (!detailMode) return []; return targets.filter(t => detailMode === "all" || (detailMode === "filled" && t.target_jp > 0) || (detailMode === "empty" && t.target_jp === 0) || (detailMode === "jp" && t.target_jp > 0)); }, [targets, detailMode]);
  const detailTitle = detailMode === "all" ? "Semua Kombinasi Target" : detailMode === "filled" ? "Target JP Sudah Diisi" : detailMode === "empty" ? "Target JP Belum Diisi" : "Total JP — Rincian";
  const detailTotal = detailMode === "jp" ? detailRows.reduce((s, t) => s + Number(t.target_jp || 0), 0) : detailRows.length;
  const nameOf = (list: Master[], id: string) => list.find(x => x.id === id)?.label ?? "—";

  // Setelah simpan berhasil, refresh view resmi (server component) di
  // TargetJpWorkspace supaya drill-down status guru/jadwal ikut ter-update --
  // bukan cuma metrik lokal panel ini.
  function afterSaved() { loadData().catch(() => {}); router.refresh(); onSaved?.(); }

  async function upload(file: File) { setBusy(true); setMessage(""); setResults([]); try { const fd = new FormData(); fd.append("file", file); const res = await fetch("/api/target-jp/import", { method: "POST", body: fd }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Gagal membaca file"); setRows(json.rows ?? []); setResults(json.results ?? []); } catch (e) { setMessage(e instanceof Error ? e.message : "Gagal membaca file"); } finally { setBusy(false); } }
  function onDrop(event: DragEvent<HTMLDivElement>) { event.preventDefault(); setDragActive(false); const file = event.dataTransfer.files?.[0]; if (file) void upload(file); }
  async function commit() { setBusy(true); setMessage(""); try { const res = await fetch("/api/target-jp/import", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows }) }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Import gagal"); setMessage(`Import berhasil: ${json.upserted} data diproses.`); setRows([]); setResults([]); afterSaved(); } catch (e) { setMessage(e instanceof Error ? e.message : "Import gagal"); } finally { setBusy(false); } }
  async function saveManual() { if (!manualContext || !manualClass || !manualSubject) { setMessage("Pilih Academic Context, Kelas, dan Mata Pelajaran terlebih dahulu."); return; } setBusy(true); setMessage(""); try { const subject = subjects.find(s => s.id === manualSubject); const res = await fetch("/api/target-jp/import", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows: [{ AcademicContext: selectedContext?.label ?? "", Kelas: selectedClass?.label ?? "", KodeMapel: subject?.code ?? "", MataPelajaran: subject?.label ?? "", TargetJP: String(manualJp) }] }) }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Gagal menyimpan Target JP"); setMessage(`Target JP ${manualJp} JP berhasil disimpan.`); afterSaved(); } catch (e) { setMessage(e instanceof Error ? e.message : "Gagal menyimpan Target JP"); } finally { setBusy(false); } }

  return <div className="space-y-6">
    <div className="rounded-xl border border-amber/30 bg-amber-50 p-4 text-sm text-ink-700"><b className="text-amber">Jalur override manual.</b> Panel ini menulis langsung ke Target JP resmi tanpa lewat rantai sumber terverifikasi (beda dari <Link href="/akademik/generate-kurikulum" className="font-semibold text-brand-700 underline">Generate Kurikulum</Link>, yang mensyaratkan sumber resmi sebelum Commit). Cocok untuk koreksi cepat satu angka — setiap perubahan tetap tercatat di Riwayat dengan nilai lama dan baru.</div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Kombinasi Target" value={totalTarget} hint="Context · Kelas · Mapel" onClick={() => setDetailMode("all")}/><Metric label="Sudah Diisi" value={filledTarget} hint="Target di atas 0 JP" onClick={() => setDetailMode("filled")}/><Metric label="Belum Diisi" value={zeroTarget} hint="Target 0 JP" onClick={() => setDetailMode("empty")}/><Metric label="Total JP" value={totalJp} hint="Klik untuk lihat rincian" onClick={() => setDetailMode("jp")}/></section>
    <section className="rounded-xl border border-border bg-surface p-5 shadow-soft"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-semibold text-ink-900">Kelola Target JP</h2><p className="mt-1 text-xs text-ink-500">Pilih konteks, kelas, dan mata pelajaran. Nilai aktif ditampilkan sebelum disimpan.</p></div>{existingJp !== undefined && <span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-semibold text-brand-700">Saat ini: {existingJp} JP</span>}</div><div className="mt-4 grid gap-3 md:grid-cols-3"><Select label="Academic Context" value={manualContext} onChange={setManualContext} options={contexts}/><Select label="Kelas" value={manualClass} onChange={setManualClass} options={classes}/><Select label="Mata Pelajaran" value={manualSubject} onChange={setManualSubject} options={subjects.map(s => ({ ...s, label: s.code ? `${s.code} · ${s.label}` : s.label }))}/></div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="mr-1 text-xs font-medium text-ink-500">Target:</span>{Array.from({ length: 11 }, (_, n) => n).map(n => <button key={n} type="button" onClick={() => setManualJp(n)} className={`h-10 min-w-11 rounded-lg border px-3 text-sm font-semibold ${manualJp === n ? "border-brand-600 bg-brand-600 text-white" : "border-border bg-surface text-ink-700 hover:bg-surface-muted"}`}>{n}</button>)}<button type="button" disabled={busy} onClick={() => void saveManual()} className="ml-auto rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Simpan Target</button></div></section>
    {message && <div className="rounded-lg border border-border bg-surface p-4 text-sm text-ink-700">{message}</div>}
    <div className="flex justify-end"><button type="button" onClick={() => setShowImport(v => !v)} className="rounded-lg border border-border px-4 py-2 text-sm font-medium text-ink-700 hover:bg-surface-muted">{showImport ? "Tutup Import File" : "Import dari File"}</button></div>
    {showImport && <section className="rounded-xl border border-border bg-surface p-5 shadow-soft"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-ink-900">Import Target JP</h2><p className="mt-1 text-xs text-ink-500">Import hanya diproses setelah validasi dan konfirmasi.</p></div><div className="flex gap-2"><a href="/api/target-jp/import" className="rounded-lg border border-border px-3 py-2 text-sm font-medium hover:bg-surface-muted">Download Template</a><label className="cursor-pointer rounded-lg bg-brand-600 px-3 py-2 text-sm font-semibold text-white hover:bg-brand-700">{busy ? "Memproses…" : "Pilih File"}<input type="file" accept=".xlsx,.xls,.csv" className="hidden" disabled={busy} onChange={e => e.target.files?.[0] && void upload(e.target.files[0])}/></label></div></div><div onDragEnter={(e) => { e.preventDefault(); setDragActive(true); }} onDragOver={(e) => { e.preventDefault(); setDragActive(true); }} onDragLeave={(e) => { e.preventDefault(); setDragActive(false); }} onDrop={onDrop} className={`mt-4 rounded-xl border-2 border-dashed p-8 text-center transition ${dragActive ? "border-brand-600 bg-brand-50" : "border-border bg-surface-muted"}`}><p className="text-sm font-semibold text-ink-800">{dragActive ? "Lepaskan file di sini" : "Tarik & lepaskan file Target JP di area ini"}</p><p className="mt-1 text-xs text-ink-500">XLSX, XLS, atau CSV · maksimal 5 MB</p></div><div className="mt-4 grid gap-2 rounded-lg bg-surface-muted p-4 text-xs text-ink-600 md:grid-cols-5">{cols.map(c => <div key={c}><span className="font-semibold text-ink-800">{c}</span></div>)}</div></section>}
    {results.length > 0 && <section className="overflow-hidden rounded-xl border border-border bg-surface shadow-soft"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-semibold text-ink-900">Validation Preview</h2><p className="text-xs text-ink-500">{results.filter(r => r.status === "valid").length} valid · {results.filter(r => r.status === "error").length} error · {results.length} baris</p></div><button disabled={busy || results.some(r => r.status === "error") || !results.some(r => r.status === "valid")} onClick={() => void commit()} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Confirm Import</button></div><div className="max-h-[520px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-surface-muted"><tr><th className="px-4 py-3">Baris</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Data</th><th className="px-4 py-3">Keterangan</th></tr></thead><tbody>{results.map(r => <tr key={r.row} className="border-t border-border"><td className="px-4 py-3">{r.row}</td><td className="px-4 py-3 font-semibold">{r.status.toUpperCase()}</td><td className="px-4 py-3">{r.data ? `${r.data.Kelas} · ${r.data.MataPelajaran || r.data.KodeMapel} · ${r.data.TargetJP} JP` : "—"}</td><td className="px-4 py-3 text-ink-500">{r.message}</td></tr>)}</tbody></table></div></section>}
    {detailMode && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-label={detailTitle} onMouseDown={e => { if (e.currentTarget === e.target) setDetailMode(null); }}><section className="flex max-h-[85vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl border border-border bg-surface shadow-2xl"><header className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="text-lg font-bold text-ink-900">{detailTitle}</h2><p className="mt-1 text-xs text-ink-500">{detailMode === "jp" ? `${detailTotal} JP total dari ${detailRows.length} data` : `${detailTotal} data`}</p></div><button type="button" onClick={() => setDetailMode(null)} className="rounded-lg border border-border px-3 py-2 text-sm font-semibold text-ink-700 hover:bg-surface-muted">Tutup</button></header><div className="overflow-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="sticky top-0 bg-surface-muted"><tr><th className="px-4 py-3">Academic Context</th><th className="px-4 py-3">Kelas</th><th className="px-4 py-3">Mata Pelajaran</th><th className="px-4 py-3">Target JP</th></tr></thead><tbody>{detailRows.map((t, i) => <tr key={`${t.academic_context_id}:${t.kelas_id}:${t.mata_pelajaran_id}:${i}`} className="border-t border-border"><td className="px-4 py-3">{nameOf(contexts, t.academic_context_id)}</td><td className="px-4 py-3">{nameOf(classes, t.kelas_id)}</td><td className="px-4 py-3">{nameOf(subjects, t.mata_pelajaran_id)}</td><td className="px-4 py-3 font-semibold">{t.target_jp} JP</td></tr>)}</tbody></table>{detailRows.length === 0 && <div className="p-10 text-center text-sm text-ink-500">Belum ada data pada kategori ini.</div>}</div></section></div>}
    <section className="rounded-xl border border-border bg-surface p-5 text-sm text-ink-600"><p className="font-semibold text-ink-900">Aturan Target JP</p><ul className="mt-2 list-disc space-y-1 pl-5"><li>Target JP harus bilangan bulat 0–10.</li><li>Academic Context, Kelas, dan Mata Pelajaran harus ditemukan.</li><li>Kode mapel diprioritaskan; nama mapel menjadi fallback.</li><li>Duplikasi dalam file ditolak.</li><li>Data existing di-upsert berdasarkan Context + Kelas + Mapel.</li></ul></section>
  </div>;
}
function Metric({ label, value, hint, onClick }: { label: string; value: number; hint: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="group rounded-xl border border-border bg-surface p-4 text-left shadow-soft transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-brand-500/30"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-ink-500">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight text-ink-900">{value}</p><p className="mt-1 text-[11px] text-ink-500">{hint}</p></div><span className="text-xs font-semibold text-brand-600 opacity-0 transition group-hover:opacity-100">Lihat detail →</span></div></button>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: Master[] }) { return <label className="flex flex-col gap-1.5 text-xs font-medium text-ink-700"><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="h-11 rounded-xl border border-border bg-surface px-3 text-sm text-ink-900"><option value="">Pilih…</option>{options.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label>; }
